accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

# 同じディレクトリ(今回はaccounts)からviews.pyをimportしている
from . import views  # .（ピリオド1つ）が同じディレクトリを表す

app_name = "accounts"

urlpatterns = [
    path(
        "signup/", views.SignupView.as_view(), name="signup"
    ),  # 第三引数のnameはパターンネームといい、signup.htmlでビューを呼び出すために記述される
    path("login/", auth_views.LoginView.as_view(template_name="accounts/login.html"), name="login"),
    # auth_views.UserLoginViewでviews.pyの UserLoginView を呼び出している
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("<str:username>/", views.UserProfileView.as_view(), name="user_profile"),
    # path(“アドレス/<値の種類: 値の引数>/”, view関数);
    # path('<str:username>/follow/', views.FollowView.as_view(), name='follow'),
    # path('<str:username>/unfollow/', views.UnFollowView, name='unfollow'),
    # path('<str:username>/following_list/', views.FollowingListView.as_view(), name='following_list'),
    # path('<str:username>/follower_list/', views.FollowerListView.as_view(), name='follower_list'),
]

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("tweets/", include("tweets.urls")),
    path("", include("welcome.urls")),
]

if settings.SQL_DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

tweets/urls.py
from django.urls import path

from . import views

app_name = "tweets"

urlpatterns = [
    path("home/", views.HomeView.as_view(), name="home"),
    # path('create/', views.TweetCreateView.as_view(), name='create'),
    # path('<int:pk>/', views.TweetDetailView.as_view(), name='detail'),
    # path('<int:pk>/delete/', views.TweetDeleteView.as_view(), name='delete'),
    # path('<int:pk>/like/', views.LikeView, name='like'),
    # path('<int:pk>/unlike/', views.UnlikeView, name='unlike'),
]

welcome/urls.py
from django.urls import path

from . import views

app_name = "welcome"
urlpatterns = [
    path("", views.WelcomeView.as_view(), name="welcome"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField()


# 引数にblank=Falseを入れる必要はない。
# なぜならデフォルトでblank=Falseとなるため。

tweets/models.py
# from django.db import models


# class Tweet(models.Model):

welcome/models.py
# from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()  # こっちで先に変数代入する！


class SignupForm(UserCreationForm):
    class Meta:
        model = User  # model = get_user_model() は NG
        # オブジェクトを作成
        fields = ("username", "email")


# User = get_user_model()；今使ってるUserモデルを取得
# class SignupForm(UserCreationForm);UserCreationFormクラスの継承
# password1, password2というフィールドはUserCreationFormの方で設定されているため、
# fieldsの欄には、Userモデルの中にある、
# blankにはできない値であるusernameとemailをセットする。

accounts/views.py
# from django.shortcuts import render
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from .forms import SignupForm

User = get_user_model()


class SignupView(CreateView):
    form_class = SignupForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy(settings.LOGIN_REDIRECT_URL)  # 遷移先の指定

    def form_valid(self, form):  # form_valid関数のオーバーライド
        response = super().form_valid(form)
        username = form.cleaned_data["username"]
        password1 = form.cleaned_data["password1"]  # passwordはキーに存在しないためpassword1にする
        user = authenticate(self.request, username=username, password=password1)
        login(self.request, user)
        return response


class UserProfileView(LoginRequiredMixin, TemplateView):
    # LoginRequiredMixinを継承するとログインしていないユーザーがprofile画面へ飛ぼうとするとログインページに遷移するようになる
    template_name = "accounts/user_profile.html"

    #  遷移先のテンプレートを指定するための変数。全てのTemplateViewクラスで設定可能
    # fields = ["username"]
    # フォームに表示するフィールドを指定する
    def get_context_data(self, **kwargs):
        # super().get_context_data(**kwargs)で親クラスの.get_context_dataを呼び出し、contextに格納
        context = super().get_context_data(**kwargs)
        # 親クラスの**kwargsで得られた辞書型のデータを一部書き換える
        context["username"] = self.kwargs["username"]
        return context

    model = User
    # レコード更新をかけるモデルを指定するための変数。
    #  ここで指定したモデルに関しては、モデル名をスネークケースに変換したものが自動的にcontextに追加される(例：Bookモデルであればcontext["book"]に格納される)。
    #  後述のform_classにてModelFormクラスを指定している場合であっても、この変数の設定は必須。

tweets/views.py
# from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.base import TemplateView


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "tweets/home.html"

welcome/views.py
from django.views.generic import TemplateView


class WelcomeView(TemplateView):
    template_name = "welcome/welcome.html"

templates/accounts/login.html
{% extends "base.html" %}
{% block title %}login{% endblock %}
{% block content %}

<form method="post">
    {{ form.as_p }} <!--formにはloginFormのインスタンスが入っている。as_pとすることで、各input要素(クラス内に定義した要素)がpタグで囲まれた状態で表示される。-->
    {% csrf_token %}
    <button type="submit">ログイン</button>
</form>
{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}
{% block content %}

<form method="post">
    {{ form.as_p }} <!--formにはSignupFormのインスタンスが入っている。as_pとすることで、各input要素(クラス内に定義した要素)がpタグで囲まれた状態で表示される。-->>
    {% csrf_token %}
    <button type="submit">ユーザー登録</button>
</form>
{% endblock %}

templates/accounts/user_profile.html
{% extends "base.html" %}
{% block title %}User Profile{% endblock %}
{% block content %}

{{view.kwargs.username}}<!--User-->
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}Twitter Clone{% endblock %}</title>
</head>

<body>
  <!-- header  -->
  <header class="mb-3">
    <nav>

      <ul><!--urlの逆引き-->
        {% if user.is_authenticated %}<!--ログイン状態-->
        <!--<li></li>で挟むと箇条書き表示になる-->
        <li><a href="{% url 'welcome:welcome' %}">Twitter Clone</a></li>
        <li><a href="{% url 'accounts:logout' %}">logout</a></li>
        <li><a href="{% url 'tweets:home' %}">home</a></li>
        <li><a href="{% url 'accounts:user_profile' user %}">user_profile</a></li>
        <!--nameの後にuserを入れることでログインしたユーザーごとのページが表示される-->
        {% else %}
        <li><a href="{% url 'accounts:signup' %}">Sign up</a></li>
        <li><a href="{% url 'accounts:login' %}">login</a></li>
        {% endif %}
        <!--ifとendifで必ず挟む-->
      </ul>
    </nav>
  </header>
  <!-- /header  -->

  <!-- main  -->
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <!-- /main  -->
</body>

</html>

templates/tweets/home.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<h1>Homeです</h1>
{% endblock %}

templates/welcome/welcome.html
{% extends "base.html" %}